name: untitled3
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sign_in_button: ^3.2.0
  google_sign_in:
  google_sign_in_web:
  firebase_core:
  firebase_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true